title: sagoiz Blog
description: Blog about everything and nothing at the same time.
url: "https://sagoiz-tech.github.io/"
github_username:  sagoiz-tech
linkedin_username: https://www.linkedin.com/in/sagoiz/


theme: minima
plugins:
  - jekyll-feed
